### ISSUE TITLE
Throttle/Brake telemetry only records at 100%

### ISSUE THREAD

**Issue by sylint19** [ovv/forzatelemetry#1]
Telemetry for the throttle and brake inputs seems to only register a change when they hit 100%. Despite an active telemetry output from SimHub, the app treats the accel/decel values as on/off (0%/100%) and no in between.
![image](https://github.com/user-attachments/assets/08a9814a-1227-4c1c-9b7e-aa95f25dfd8d)

**Comment by ovv** [comment]
Thanks for the report :+1: . It should be fixed, let me know if you see others inaccuracies.
